package hi

import "encoding/json"

// Channel Messages are ways of dictating what the scope of a message should be
const (
	ChannelGame    = "GAME"
	ChannelGlobal  = "GLOBAL"
	ChannelPlayer  = "PLAYER"
	ChannelPrivate = "PRIVATE"
)

// MessageToPlayer holds the type required for games to pass around as a shared type object
type MessageToPlayer struct {
	Type         string          `json:"type"`
	EventChannel string          `json:"event_channel,omitempty"`
	GameID       string          `json:"game_id,omitempty"`
	Message      json.RawMessage `json:"message,omitempty"`
}

// MessageFromPlayer is an event generated by a player in a game to be fed into a game or the hub for processing.
type MessageFromPlayer struct {
	Type         string `json:"type"`
	EventChannel string `json:"event_channel,omitempty"`
	GameID       string `json:"game_id,omitempty"`
	Message      string `json:"message,omitempty"`
}
