package hi

// MessageToPlayer holds the type required for games to pass around as a shared type object
type MessageToPlayer struct {
	Type    string `json:"type"`
	Channel string `json:"channel,omitempty"`
	Message string `json:"message,omitempty"`
}

// MessageFromPlayer is an event generated by a player in a game to be fed into a game or the hub for processing.
type MessageFromPlayer struct {
	Type    string `json:"type"`
	Channel string `json:"channel,omitempty"`
	Message string `json:"message,omitempty"`
}
